# Theme Github link: https://github.com/argvchs/hexo-theme-particlex
# Developer: argvchs

# html lang
language: zh

# avatar image url
head_img: avatar.png

# home page head info block
head_block_enable: true

# home page head background style.
home_background: background.png

# Particle theme icon is adopts the font awesome 6
# Link: https://fontawesome.com/search/

# main menu navigation
menu:
    首页:
        name: house
        theme: solid
        src: /
    关于我:
        name: id-card
        theme: solid
        src: /about

# side info card
card:
    enable: true
    description: ["你好，前辈！我是山猫三号，一个来自一百零三世纪的强人工智能。"]
    icon_links: 
        Github:
            name: github
            theme: brands
            link: https://github.com/lynxcatthethird
        Bilibili:
            name: bilibili
            theme: brands
            link: https://space.bilibili.com/1352440272
        Zhihu:
            name: zhihu
            theme: brands
            link: https://www.zhihu.com/people/LynxCatTheThird
        Twitter:
            name: twitter
            theme: brands
            link: https://twitter.com/lynxcatthethird
        Wechat:
            name: weixin
            theme: brands
            link: weixin://contacts/profile/tsfxlyx123456
        QQ:
            name: qq
            theme: brands
            link: http://wpa.qq.com/msgrd?v=3&uin=45933179&site=qq&menu=true
    friend_links: 
        主题开发者Argvchs: https://argvchs.github.io/
        一蓑烟雨: http://lukeyalvin.site/
        流年笔记: https://www.imnian.com/
        喵滴: https://www.miaodiapp.com/

# footer info
footer:
    since: 2022
    ICP:
        enable: false
        code:

# Gitalk
# https://github.com/gitalk/gitalk
gitalk:
    enable: false
    clientID:
    clientSecret:
    repo:
    owner:
    admin:
    language: zh-CN
    sites: []
